version: '3'
services:
  core:
    image: ghcr.io/eivarin/coreemu:coreemu-9.2.1
    container_name: core
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./src:/src
      - ./.bashrc:/root/.bashrc
    user: "${UID}:${GID}"
    privileged: true
    stdin_open: true 
    tty: true